# Generated by Django 5.0.3 on 2024-09-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
