# Generated by Django 4.2.10 on 2024-11-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('password', models.CharField(max_length=30)),
                ('passW', models.CharField(max_length=30)),
            ],
        ),
    ]
