# Generated by Django 5.1.5 on 2025-02-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='image',
            field=models.ImageField(null=True, upload_to='cvProject/images/'),
        ),
    ]
