# Generated by Django 5.1.4 on 2025-03-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='category',
            field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('classical', 'Classical')], default='rock', max_length=50),
        ),
    ]
