# Generated by Django 5.1.5 on 2025-02-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvProject', '0002_concert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cvProject/images/'),
        ),
    ]
