# Generated by Django 5.1.4 on 2025-03-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvProject', '0002_concert_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit',
            field=models.FloatField(default=10000),
        ),
    ]
