# Generated by Django 5.1.5 on 2025-02-06 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvProject', '0003_concert_capacity_alter_concert_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cvProject/images/')),
                ('gender', models.IntegerField(choices=[('man', 'مرد'), ('woman', 'خانم')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
