# Generated by Django 4.2.10 on 2025-02-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvProject', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cvProject/files/'),
        ),
    ]
