# Generated by Django 5.1.5 on 2025-02-06 18:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvProject', '0004_profileuser_delete_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileUser',
            new_name='Profile',
        ),
    ]
