# Generated by Django 4.2.10 on 2025-02-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvProject', '0004_contactus_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/files/'),
        ),
    ]
