# Generated by Django 5.1.5 on 2025-02-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvProject', '0005_rename_profileuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'مرد'), (2, 'خانم')], default=1),
        ),
    ]
