# Generated by Django 5.0.3 on 2024-03-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1500)),
            ],
        ),
    ]
