# Generated by Django 4.2.10 on 2024-06-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='test',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
