# Generated by Django 4.2.10 on 2024-06-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_users_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='test',
        ),
    ]
