# Generated by Django 4.2.10 on 2024-06-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('file', models.FileField(upload_to='data/')),
            ],
        ),
    ]
