# Generated by Django 4.2.10 on 2024-06-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tamrin_Search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
