# Generated by Django 4.2.10 on 2024-06-28 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tamrin_Search', '0002_alter_data_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='file',
            new_name='image',
        ),
    ]
