# Generated by Django 4.2.10 on 2024-07-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tamrin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='ProfileUser',
        ),
    ]
